// stocktrade-react/src/components/stocks/Stock.js
import React, { Component } from 'react';
import {computed, action, observable} from 'mobx';
import {observer,inject} from "mobx-react";
import stocksStore from "../../stores/modules/stocks";

import "./Stock.css";

@inject("stores") @observer
class Stock extends Component {

    @observable quantity = 0;

    constructor(props) {
        super(props);
        this.changeQuantity = ::this.changeQuantity;
        this.buyStock = ::this.buyStock;
    }
    @computed get funds(){
        return this.props.stores.portfolioStore.funds;
    }
    @computed get buttonDisabled(){
        return this.insufficientFunds || this.quantity <=0;
    }
    @computed get insufficientFunds(){
        return (this.quantity * this.props.stock.price) > this.funds;
    }
    @action changeQuantity = (event) => {
        this.quantity = event.target.value;
    }
    @action setQuantity = (quantity) => {
        this.quantity = quantity;
    }
    changeQuantity(event) {
        this.setQuantity(event.target.value);
    }
    buyStock(){
        const order = {
            stockId: this.props.stock.id,
            stockPrice: this.props.stock.price,
            quantity: this.quantity
        };
        this.props.stores.portfolioStore.buyStock(order);
        this.setQuantity(0);
    }
    render() {
        const { stock } = this.props;
        const quantityClass = "form-control " + (this.insufficientFunds? "danger": "");
        const buttonText = this.insufficientFunds? 'Insufficient Funds' : 'Buy';
        return (
          <div className="col-sm-6 col-md-4">
            <div className="panel panel-success">
                <div className="panel-heading">
                    <h3 className="panel-title">
                         {this.props.stock.name }
                        <small>(Price: { this.props.stock.price })</small>
                    </h3>
                </div>
                <div className="panel-body">
                    <div className="pull-left">
                        <input
                                type="number"
                                className={quantityClass}
                                placeholder="Quantity"
                                onChange={this.changeQuantity}
                                value={this.quantity}
                        />
                    </div>
                    <div className="pull-right">
                        <button
                                className="btn btn-success"
                                onClick={this.buyStock}
                                disabled={this.buttonDisabled}
                        >
                        {buttonText}
                        </button>
                    </div>
                </div>
            </div>
        </div>
        );
    }
}

export default Stock;

// stocktrade-vue/src/components/stocks/Stock.vue
<template>
    <div class="col-sm-6 col-md-4">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">
                    {{ stock.name }}
                    <small>(Price: {{ stock.price }})</small>
                </h3>
            </div>
            <div class="panel-body">
                <div class="pull-left">
                    <input
                            type="number"
                            class="form-control"
                            placeholder="Quantity"
                            v-model="quantity"
                            :class="{danger: insufficientFunds}"
                    >
                </div>
                <div class="pull-right">
                    <button
                            class="btn btn-success"
                            @click="buyStock"
                            :disabled="insufficientFunds || quantity <= 0"
                    >{{ insufficientFunds ? 'Insufficient Funds' : 'Buy' }}
                    </button>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
    export default {
        props: ['stock'],
        data() {
            return {
                quantity: 0
            }
        },
        computed: {
            funds() {
                return this.$store.getters.funds;
            },
            insufficientFunds() {
                return this.quantity * this.stock.price > this.funds;
            }
        },
        methods: {
            buyStock() {
                const order = {
                    stockId: this.stock.id,
                    stockPrice: this.stock.price,
                    quantity: this.quantity
                };
                this.$store.dispatch('buyStock', order);
                this.quantity = 0;
            }
        }
    }
</script>

<style scoped>
    .danger {
        border: 1px solid red;
    }
</style>
